### ISSUE TITLE
Bug. Dont work mount of the data 

### ISSUE THREAD

**Issue by Anonym3310** [Mirivan/material_hunter#2]
![Screenshot_20230304-212158183](https://user-images.githubusercontent.com/71279721/222936864-9780023b-32d2-4b50-bb91-40ae38f14910.jpg)
System: CrDroid 6.25 android 10
If you need somthings logs tell me and I send you

Если вам нужны какие-то логи сообщите мне и я отправлю их вам

**Comment by Anonym3310** [comment]
![Screenshot_20230305-104413590](https://user-images.githubusercontent.com/71279721/222937081-a889f1f3-8260-47bc-b538-9ae179b3fe78.jpg)
 Версия апк
Version apk

**Comment by TMayfine** [comment]
We are aware of this bug, it does not appear on all devices. The function will be marked as dangerous, as it will cause significant errors on a successful mount.
